<?php include 'header.php'; ?>

<div class="glass-card animate-on-scroll" style="max-width: 800px; margin: 0 auto; text-align: center;">
    <h1>Chyť Marka</h1>
    <p>Marek neustále odbíhá na další koncert! Klikni na něj dřív, než zmizí.</p>
    
    <div style="margin: 1rem 0; font-size: 1.5rem; font-weight: bold; color: var(--primary-red);">
        Skóre: <span id="score">0</span> | Čas: <span id="time">30</span>s
    </div>

    <div id="game-board" style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; max-width: 450px; margin: 0 auto;">
        <!-- Holes generated by JS -->
    </div>
    
    <button id="startBtn" class="btn" style="margin-top: 2rem;">Start Hry</button>
    <a href="hry.php" class="btn btn-outline" style="margin-top: 2rem; margin-left: 10px;">Zpět na hry</a>
</div>

<style>
    .hole {
        width: 100%;
        aspect-ratio: 1;
        background-color: rgba(255, 255, 255, 0.5);
        border: 3px solid var(--primary-red);
        border-radius: 50%;
        position: relative;
        overflow: hidden;
        box-shadow: inset 0 5px 10px rgba(0,0,0,0.1);
    }
    
    .marek {
        width: 80%;
        height: 80%;
        background-image: url('https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/e7/00/e9/e700e9c5-2323-d759-5156-775dd96e9f2b/cover.jpg/400x400bb.jpg');
        background-size: cover;
        background-position: center;
        border-radius: 50%;
        position: absolute;
        bottom: -100%;
        left: 10%;
        transition: bottom 0.2s ease-out;
        cursor: crosshair;
        pointer-events: none;
    }
    
    .hole.up .marek {
        bottom: 10%;
        pointer-events: auto;
    }
</style>

<script>
    const board = document.getElementById('game-board');
    const scoreDisplay = document.getElementById('score');
    const timeDisplay = document.getElementById('time');
    const startBtn = document.getElementById('startBtn');
    
    let holes = [];
    let score = 0;
    let time = 30;
    let isPlaying = false;
    let gameTimer;
    let moleTimer;
    let lastHole;

    // Create holes
    for (let i = 0; i < 9; i++) {
        let hole = document.createElement('div');
        hole.classList.add('hole');
        
        let marek = document.createElement('div');
        marek.classList.add('marek');
        
        marek.addEventListener('mousedown', (e) => {
            if (!e.isTrusted) return; // Prevent fake clicks
            score++;
            scoreDisplay.innerText = score;
            hole.classList.remove('up');
            
            // Effect on hit
            marek.style.backgroundImage = "url('https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/60/c9/51/60c9515f-0031-40c8-c18b-8bcf83d42c2c/cover.jpg/400x400bb.jpg')";
            setTimeout(() => {
                marek.style.backgroundImage = "url('https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/e7/00/e9/e700e9c5-2323-d759-5156-775dd96e9f2b/cover.jpg/400x400bb.jpg')";
            }, 300);
        });
        
        hole.appendChild(marek);
        board.appendChild(hole);
        holes.push(hole);
    }

    function randomTime(min, max) {
        return Math.round(Math.random() * (max - min) + min);
    }

    function randomHole(holesList) {
        const idx = Math.floor(Math.random() * holesList.length);
        const hole = holesList[idx];
        if (hole === lastHole) {
            return randomHole(holesList);
        }
        lastHole = hole;
        return hole;
    }

    function peep() {
        const timeToPeep = randomTime(500, 1000);
        const hole = randomHole(holes);
        hole.classList.add('up');
        
        moleTimer = setTimeout(() => {
            hole.classList.remove('up');
            if (isPlaying) peep();
        }, timeToPeep);
    }

    function startGame() {
        if(isPlaying) return;
        score = 0;
        time = 30;
        scoreDisplay.innerText = score;
        timeDisplay.innerText = time;
        isPlaying = true;
        startBtn.disabled = true;
        
        peep();
        
        gameTimer = setInterval(() => {
            time--;
            timeDisplay.innerText = time;
            if (time <= 0) {
                clearInterval(gameTimer);
                isPlaying = false;
                startBtn.disabled = false;
                startBtn.innerText = "Hrát znovu";
                setTimeout(() => alert(`Konec hry! Tvoje skóre je ${score}.`), 100);
            }
        }, 1000);
    }

    startBtn.addEventListener('click', startGame);
</script>

<?php include 'footer.php'; ?>
